# Generated by Django 4.0.6 on 2022-08-02 10:45

import bookapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=50, unique=True)),
                ('book_title', models.CharField(max_length=100)),
                ('book_category', models.CharField(choices=[('theology', 'THEOLOGY'), ('education', 'EDUCATION'), ('music', 'MUSIC'), ('programming', 'PROGRAMMING'), ('sports', 'SPORT')], max_length=100)),
                ('book_author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='borrowing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('returning_date', models.DateField(default=bookapp.models.expiration)),
                ('booktitle', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='bookapp.bookcategory')),
                ('borrowed_by', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
